# Repo: `azureDevOpsPrototypes/azureDevOpsPrototypes`
# File: azure-pipeline.yaml
#
# Desc:
# This sample shows how to pass groups of variables into a template.
# This example comes from:
# https://medium.com/microsoftazure/how-to-pass-variables-in-azure-pipelines-yaml-tasks-5c81c5d31763
#
# Usage:
# This is useful when you have a job template which produces variables that need to be passed to following jobs and
# job templates.

# Variables:
# Global variables can be defined below.
##
# These are the only branches we will run the pipeline for.
trigger:
  #batch: true
  branches:
    include:
    - develop/*
    - feature/*
    - master
    exclude:
    - releases/old*
  paths:
    exclude:
    - 'docs/' # dont trigger when we update some Markdown.
    - 'README.md'
pr: none # Don't run against PRs

# Global Variables that are common for all stages, jobs and steps.
variables:
  VMIMAGENAME: 'ubuntu-latest'
  REPO_NAME: '$(Build.Repository.Name)'
  BRANCH_NAME: '$(Build.SourceBranchName)'
  System.Debug: 'true' #set to true if you want verbose pipeline output.

# Use a repo as a resource for pipeline templates to help us keep DRY.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops
#resources:
#  repositories:
#    - repository: templates
#      type: git
#      name: 'Azure DevOps Utility/AzureDevOpsTemplates'
#      # If you want to use a particular, fixed version of the template, be sure to pin to a ref. Refs are either
#      # branches (refs/heads/<name>) or tags (refs/tags/<name>). If you want to pin a specific commit, first create a
#      # tag pointing to that commit, then pin to that tag.
#      #ref: refs/tags/v1.5 # optional ref to pin to
#      ref: refs/heads/develop/bes067

# pipeline display name
name: $(BuildDefinitionName)_$(SourceBranchName).$(DayOfYear)$(Rev:.r)

stages:

  - stage: stage00
    pool:
      vmImage: '$(VMIMAGENAME)'
    displayName: 'Stage 00'
    #condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/develop/')
    variables:
      STAGE00_VAR00: 'Rodney Dangerfield from stage00 static var'

    jobs:
      - job: job00
        pool:
          vmImage: '$(VMIMAGENAME)'
        displayName: 'Job 00'
        #dependsOn:
        #condition:
        variables:
          STAGE00_JOB00_VAR00: 'Charlie Chaplan from job00 static VAR'

        steps:
          - checkout: none
          # Sets BASH00STEP00_VAR00 to "BASH00STEP00_VAR00_VALUE", then mark it as output variable
          - bash: |
              echo #
              echo #
              STAGE00_JOB00_BASH00_VAR00="Larry_from_stage00_job00"
              STAGE00_JOB00_BASH00_VAR01="Moe_from_stage00_job00"
              STAGE00_JOB00_BASH00_VAR02="Curly_from_stage00_job00"
              TF_VAR_LOCATION="australiaeast"
              echo "##vso[task.setvariable variable=STAGE00_JOB00_BASH00_VAR00;isOutput=true]$STAGE00_JOB00_BASH00_VAR00"
              echo "##vso[task.setvariable variable=STAGE00_JOB00_BASH00_VAR01;isOutput=true]$STAGE00_JOB00_BASH00_VAR01"
              echo "##vso[task.setvariable variable=STAGE00_JOB00_BASH00_VAR02;isOutput=true]$STAGE00_JOB00_BASH00_VAR02"
              echo "##vso[task.setvariable variable=TF_VAR_LOCATION;isOutput=true]$TF_VAR_LOCATION"
            name: job00Bash00
            displayName: 'setting var and mark as output'

          # Show output variable in the same job
          - bash: |
              echo #
              echo #
              echo "Output from job00Bash01"
              echo "STAGE00_JOB00_BASH01_VAR00: contains $(job00Bash00.STAGE00_JOB00_BASH00_VAR00)"
              echo "STAGE00_JOB00_BASH01_VAR01: contains $(job00Bash00.STAGE00_JOB00_BASH00_VAR01)"
              echo "STAGE00_JOB00_BASH01_VAR02: contains $(job00Bash00.STAGE00_JOB00_BASH00_VAR02)"
              echo "STAGE00_JOB00_BASH01_VAR03: contains $(job00Bash00.TF_VAR_LOCATION)"
            name: job00Bash01
            displayName: 'display var label and value'

          - task: Bash@3
            displayName: 'env dump'
            inputs:
              targetType: 'inline'
              script: 'env | sort | grep 00'

      # define our second job which will pull a variable out of the first job
      - job: job01
        pool:
          vmImage: '$(VMIMAGENAME)'
        displayName: 'Job 01'
        dependsOn: job00
        variables:
          STAGE00_JOB01_VAR00: 'Bill Murray from stage00 job01 static var'
          # here we tell the pipeline yaml to go and get the var we want from job00 outputs.
          STAGE00_JOB01_VAR01: $[ dependencies.job00.outputs['job00Bash00.STAGE00_JOB00_BASH00_VAR00'] ]
          STAGE00_JOB01_VAR02: $[ dependencies.job00.outputs['job00Bash00.STAGE00_JOB00_BASH00_VAR01'] ]
          STAGE00_JOB01_VAR03: $[ dependencies.job00.outputs['job00Bash00.STAGE00_JOB00_BASH00_VAR02'] ]

        steps:
          - checkout: none
          # The variable is now available for expansion within the job
          - bash: |
              echo "dependencies.job00.outputs['job00Bash00.STAGE00_JOB00_BASH00_VAR00']: $(STAGE00_JOB01_VAR01)"
            name: job01Bash00
            displayName: 'display var label and value from job00'

          # To send the variable to the script as environmental variable, it needs to be set in the env dictionary
          - bash: |
              echo "STAGE00_JOB01_VAR01: $STAGE00_JOB01_VAR01"
            name: job01Bash01
            displayName: 'display var label and value from job00 from bash env assignment'
            env:
              STAGE00_JOB01_VAR01: $(STAGE00_JOB01_VAR01) # here we insert the variable into the env for this shell.

          - task: Bash@3
            displayName: 'env dump'
            inputs:
              targetType: 'inline'
              script: 'env | sort | grep 00'

      # here we pass our three job00 variables into a template for use in there.
      - template: ./multiple-vars-into-a-child-template.yaml
        parameters:
          #
          # variables and parameters can be passed using one of two syntax formats.
          # https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#variables
          # FIXME - I have been unable to confirm if your are able to use both formats together. Gut feel is that its not a good practice.
          #         FIXME Ive experimented with it and it may have an affect on how parameter expansion occurs in the template.
          # FIXME - Experiments have shown that you cannot use the dependency reference in a mapping format.
          #         FIXME https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies
          #         FIXME The dependency reference syntax docs dont mention this. 🙄
          # FIXME - Rules:
          #         FIXME - dependency references must use Sequence Format (see additionalVariables0)
          #         FIXME - static variable references and/or template expansion references can use Mapping Format or
          #
          # additionalVariables0 using `Sequence Format`
          additionalVariables0:
            # here we tell the pipeline yaml to go and get the var we want from job00 outputs.
            STAGE00_TEMPL_ADDITIONALVARIABLES_VAR00: $[ dependencies.job00.outputs['job00Bash00.STAGE00_JOB00_BASH00_VAR00'] ]
            STAGE00_TEMPL_ADDITIONALVARIABLES_VAR01: $[ dependencies.job00.outputs['job00Bash00.STAGE00_JOB00_BASH00_VAR01'] ]
            STAGE00_TEMPL_ADDITIONALVARIABLES_VAR02: $[ dependencies.job00.outputs['job00Bash00.STAGE00_JOB00_BASH00_VAR02'] ]
            STAGE00_TEMPL_ADDITIONALVARIABLES_VAR03: 'TMPL_CONTENTS_STATIC_VAR_03'
            TF_VAR_LOCATION: $[ dependencies.job00.outputs['job00Bash00.TF_VAR_LOCATION'] ]
          # additionalVariables1 uses `Mapping Format`
          additionalVariables1: { STAGE00_TEMPL_ADDITIONALVARIABLES_VAR04: 'TMPL_CONTENTS_STATIC_VAR_04', STAGE00_TEMPL_ADDITIONALVARIABLES_VAR05: 'TMPL_CONTENTS_STATIC_VAR_05'}
